version: '3.7'

services:

  auth:
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: auth
    volumes:
      - $CONFIG_DIRECTORY:/etc/wow
      - $LOG_DIRECTORY:/wowlogs
    ports:
      - $AUTH_PORT:3724
    env_file:
      - ../.env

  world:
    restart: always
    build:
        context: ../
        dockerfile: docker/Dockerfile
        target: world
    volumes:
        - $CONFIG_DIRECTORY:/etc/wow
        - $DATA_DIRECTORY:/wowdata
        - $LOG_DIRECTORY:/wowlogs
    ports: 
        - $WORLD_PORT:8085
    env_file:
        - ../.env

  apache:
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: apache
    ports:
      - $APACHE_PORT:80
    env_file:
      - ../.env      

  php:
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: php
    env_file:
      - ../.env     

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
        - $DB_FILES:/var/lib/mysql